spring:
  application:
    name: "todo-management"

  datasource:
    url: jdbc:mysql://localhost:3306/todosDB
    username:
    password:

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
